# Generated by Django 6.0 on 2026-03-02 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Project', 'Project'), ('Food', 'Food'), ('Community Programme', 'Community Programme'), ('Medical', 'Medical'), ('Relief', 'Relief')], default='Project', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, help_text='CTA = Call To Action button text, e.g., Donate', max_length=48)),
                ('cta_url', models.URLField(blank=True, help_text='Link opened when CTA is clicked')),
                ('highlight', models.BooleanField(default=True, help_text='Show in marquee')),
                ('feature', models.BooleanField(default=True, help_text='Feature in carousel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
